services:
  - type: web
    name: cloudedit
    plan: free
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
    healthCheckPath: /
